on: push
name: CI

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Set up Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Use current yarn
        run: yarn set version 3.x
      - name: yarn install
        run: yarn install
      - name: Deploy to gh-pages
        if: github.ref == 'refs/heads/master'
        run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
